-- Intentionally empty.
--
-- Development sample data must not be loaded automatically by Supabase CLI
-- resets, linked resets, preview branches, or `db push --include-seed`.
--
-- Use the explicit local-only scripts from the repository root instead:
--   npm run seed:local:data
--   npm run seed:local
